// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuiMW_zNgoURe1sQqIxNvxPEfzAubfgSU',
    appId: '1:975831608713:android:e0aadb2cb372efa4ae0558',
    messagingSenderId: '975831608713',
    projectId: 'report-a-child',
    storageBucket: 'report-a-child.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWwEAQVyC96DFxGYeR1Y35WYRgv-5zVp8',
    appId: '1:975831608713:ios:b610765eb06dbb18ae0558',
    messagingSenderId: '975831608713',
    projectId: 'report-a-child',
    storageBucket: 'report-a-child.appspot.com',
    androidClientId: '975831608713-54k8ras9dp00koediu67r3imhvs0qugc.apps.googleusercontent.com',
    iosClientId: '975831608713-qo8ek54grgalvdutp6jcborb2jgtmv9q.apps.googleusercontent.com',
    iosBundleId: 'com.mundoultra.salvavidas',
  );
}
